version: '3.1'

services:
  db:
    image: postgres:14.15-bookworm
    restart: always
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: root
      POSTGRES_DB: gin_crud
    ports:
      - "54321:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
